# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Piano keys' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'AudioKit', '~> 3.7'

end
