# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'Convertor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
  pod 'Alamofire', '~> 4.4.0'
  pod 'SwiftyJSON'

 

end
